In [106]:
import pandas as pd
import numpy as np

#Question 1

In [107]:
!python3 -m install pip

/usr/bin/python3: No module named install

In [108]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.10/dist-packages (8.3.0)

In [109]:
import mysql.connector

In [110]:
connection = mysql.connector.connect(
    host= 'database-comp3162.cqb8o27401uq.us-east-2.rds.amazonaws.com',
    user='comp3162user',
    password = 'Password876',
    port=3306,
    database='comp3162'
)

In [111]:
cursor = connection.cursor()

In [112]:
cursor.execute('SELECT * FROM Patients')

In [113]:
#cursor.execute("SHOW COLUMNS FROM Patients")

In [114]:
rows= cursor.fetchall()

In [115]:
rows

[(1, 45, 'Male', 25.6, 120, 190, 'Normal', 'Yes', 'Positive'),
 (2, 55, 'Female', 29.8, 140, 220, 'High', 'No', 'Negative'),
 (3, 60, 'Male', 27.3, 130, 210, 'Normal', 'Yes', 'Positive'),
 (4, 35, 'Female', 22.5, 110, 180, 'Normal', 'No', 'Negative'),
 (5, 50, 'Male', 31.1, 150, 240, 'High', 'Yes', 'Positive'),
 (6, 65, 'Male', 26.5, 125, 200, 'High', 'Yes', 'Positive'),
 (7, 40, 'Female', 24.9, 115, 170, 'Normal', 'No', 'Negative'),
 (8, 70, 'Male', 27.9, 135, 230, 'High', 'Yes', 'Positive'),
 (9, 58, 'Female', None, 130, 210, 'Normal', 'Yes', 'Positive'),
 (10, 45, 'Male', 28.3, None, 220, 'High', 'No', 'Negative'),
 (11, 53, 'Female', 26.8, 125, None, 'Normal', 'No', 'Negative'),
 (12, 62, 'Male', 30.5, 145, 240, None, 'Yes', 'Positive'),
 (13, 47, 'Male', 25.1, 122, 195, 'Normal', 'Yes', 'Positive'),
 (14, 57, 'Female', 27.4, 138, 215, 'Normal', 'No', 'Negative'),
 (15, 64, 'Male', 28.6, 132, 225, 'High', 'Yes', 'Positive'),
 (16, 38, 'Female', 23.8, 114, 175, 'Normal', 'No', 'Negative'),
 (17, 48, 'Male', 30.2, 148, 230, 'High', 'Yes', 'Positive'),
 (18, 69, 'Male', 26.2, 128, 205, 'Normal', 'Yes', 'Positive'),
 (19, 42, 'Female', 29.7, 142, 218, 'High', 'No', 'Negative'),
 (20, 56, 'Male', 24.5, 123, 198, 'Normal', 'Yes', 'Positive'),
 (21, 61, 'Female', 27.9, 136, 227, 'Normal', 'No', 'Negative'),
 (22, 36, 'Male', 25.9, 126, 202, 'High', 'Yes', 'Positive'),
 (23, 52, 'Male', 22.3, 108, 178, 'Normal', 'No', 'Negative'),
 (24, 63, 'Female', 30.4, 144, 235, 'High', 'Yes', 'Positive'),
 (25, 41, 'Male', 27.1, 134, 215, 'Normal', 'Yes', 'Positive'),
 (26, 59, 'Female', 26.6, 130, 212, 'Normal', 'No', 'Negative'),
 (27, 68, 'Male', 28.9, 139, 222, 'High', 'Yes', 'Positive'),
 (28, 37, 'Male', 24.2, 120, 192, 'Normal', 'Yes', 'Positive'),
 (29, 49, 'Female', 29.5, 141, 217, 'High', 'No', 'Negative'),
 (30, 54, 'Male', 25.8, 124, 200, 'Normal', 'Yes', 'Positive'),
 (31, 66, 'Female', 28.2, 137, 224, 'Normal', 'No', 'Negative'),
 (32, 39, 'Male', 27.6, 133, 210, 'High', 'Yes', 'Positive'),
 (33, 51, 'Male', 23.7, 109, 180, 'Normal', 'No', 'Negative'),
 (34, 70, 'Female', 30.1, 147, 231, 'High', 'Yes', 'Positive'),
 (35, 43, 'Male', 26.4, 129, 208, 'Normal', 'Yes', 'Positive'),
 (36, 58, 'Female', 29.3, 140, 216, 'High', 'No', 'Negative'),
 (37, 67, 'Male', 26.7, 131, 214, 'Normal', 'Yes', 'Positive'),
 (38, 44, 'Male', 25.7, 121, 196, 'Normal', 'Yes', 'Positive'),
 (39, 60, 'Female', 28.7, 135, 226, 'Normal', 'No', 'Negative'),
 (40, 50, 'Male', 24.4, 125, 198, 'High', 'Yes', 'Positive'),
 (41, 65, 'Female', 27.8, 138, 220, 'High', 'No', 'Negative'),
 (42, 35, 'Male', 26.1, 127, 204, 'Normal', 'Yes', 'Positive'),
 (43, 55, 'Male', 22.8, 111, 182, 'Normal', 'No', 'Negative'),
 (44, 63, 'Female', 30.6, 146, 236, 'High', 'Yes', 'Positive'),
 (45, 40, 'Male', 27.4, 132, 216, 'Normal', 'Yes', 'Positive'),
 (46, 57, 'Female', 26.9, 131, 213, 'Normal', 'No', 'Negative'),
 (47, 66, 'Male', 28.1, 136, 223, 'High', 'Yes', 'Positive'),
 (48, 38, 'Male', 24.3, 119, 194, 'Normal', 'Yes', 'Positive'),
 (49, 52, 'Female', 29.6, 143, 219, 'High', 'No', 'Negative'),
 (50, 68, 'Male', 25.5, 124, 199, 'Normal', 'Yes', 'Positive')]

In [116]:
"""('PatientID', 'int', 'NO', 'PRI', None, ''),
 ('Age', 'int', 'YES', '', None, ''),
 ('Sex', 'text', 'YES', '', None, ''),
 ('BMI', 'double', 'YES', '', None, ''),
 ('BloodPressure', 'int', 'YES', '', None, ''),
 ('Cholesterol', 'int', 'YES', '', None, ''),
 ('BloodSugar', 'text', 'YES', '', None, ''),
 ('FamilyHistory', 'text', 'YES', '', None, ''),
 ('CancerStatus', 'text', 'YES', '', None, '')]"""

"('PatientID', 'int', 'NO', 'PRI', None, ''),\n ('Age', 'int', 'YES', '', None, ''),\n ('Sex', 'text', 'YES', '', None, ''),\n ('BMI', 'double', 'YES', '', None, ''),\n ('BloodPressure', 'int', 'YES', '', None, ''),\n ('Cholesterol', 'int', 'YES', '', None, ''),\n ('BloodSugar', 'text', 'YES', '', None, ''),\n ('FamilyHistory', 'text', 'YES', '', None, ''),\n ('CancerStatus', 'text', 'YES', '', None, '')]"

In [117]:
df = pd.DataFrame(rows, columns =['PatientID', 'Age','Sex', 'BMI','BloodPressure', 'Cholesterol','BloodSugar', 'FamilyHistory','CancerStatus'])

In [118]:
df= df.set_index('PatientID')

In [119]:
df

,Age,Sex,BMI,BloodPressure,Cholesterol,BloodSugar,FamilyHistory,CancerStatus
PatientID,,,,,,,,
1,45,Male,25.6,120.0,190.0,Normal,Yes,Positive
2,55,Female,29.8,140.0,220.0,High,No,Negative
3,60,Male,27.3,130.0,210.0,Normal,Yes,Positive
4,35,Female,22.5,110.0,180.0,Normal,No,Negative
5,50,Male,31.1,150.0,240.0,High,Yes,Positive
6,65,Male,26.5,125.0,200.0,High,Yes,Positive
7,40,Female,24.9,115.0,170.0,Normal,No,Negative
8,70,Male,27.9,135.0,230.0,High,Yes,Positive
9,58,Female,NaN,130.0,210.0,Normal,Yes,Positive
10,45,Male,28.3,NaN,220.0,High,No,Negative
11,53,Female,26.8,125.0,NaN,Normal,No,Negative
12,62,Male,30.5,145.0,240.0,None,Yes,Positive
13,47,Male,25.1,122.0,195.0,Normal,Yes,Positive
14,57,Female,27.4,138.0,215.0,Normal,No,Negative
15,64,Male,28.6,132.0,225.0,High,Yes,Positive
16,38,Female,23.8,114.0,175.0,Normal,No,Negative
17,48,Male,30.2,148.0,230.0,High,Yes,Positive
18,69,Male,26.2,128.0,205.0,Normal,Yes,Positive
19,42,Female,29.7,142.0,218.0,High,No,Negative
20,56,Male,24.5,123.0,198.0,Normal,Yes,Positive
21,61,Female,27.9,136.0,227.0,Normal,No,Negative
22,36,Male,25.9,126.0,202.0,High,Yes,Positive
23,52,Male,22.3,108.0,178.0,Normal,No,Negative
24,63,Female,30.4,144.0,235.0,High,Yes,Positive
25,41,Male,27.1,134.0,215.0,Normal,Yes,Positive
26,59,Female,26.6,130.0,212.0,Normal,No,Negative
27,68,Male,28.9,139.0,222.0,High,Yes,Positive
28,37,Male,24.2,120.0,192.0,Normal,Yes,Positive
29,49,Female,29.5,141.0,217.0,High,No,Negative
30,54,Male,25.8,124.0,200.0,Normal,Yes,Positive
31,66,Female,28.2,137.0,224.0,Normal,No,Negative
32,39,Male,27.6,133.0,210.0,High,Yes,Positive
33,51,Male,23.7,109.0,180.0,Normal,No,Negative
34,70,Female,30.1,147.0,231.0,High,Yes,Positive
35,43,Male,26.4,129.0,208.0,Normal,Yes,Positive
36,58,Female,29.3,140.0,216.0,High,No,Negative
37,67,Male,26.7,131.0,214.0,Normal,Yes,Positive
38,44,Male,25.7,121.0,196.0,Normal,Yes,Positive
39,60,Female,28.7,135.0,226.0,Normal,No,Negative
40,50,Male,24.4,125.0,198.0,High,Yes,Positive
41,65,Female,27.8,138.0,220.0,High,No,Negative
42,35,Male,26.1,127.0,204.0,Normal,Yes,Positive
43,55,Male,22.8,111.0,182.0,Normal,No,Negative
44,63,Female,30.6,146.0,236.0,High,Yes,Positive
45,40,Male,27.4,132.0,216.0,Normal,Yes,Positive
46,57,Female,26.9,131.0,213.0,Normal,No,Negative
47,66,Male,28.1,136.0,223.0,High,Yes,Positive
48,38,Male,24.3,119.0,194.0,Normal,Yes,Positive
49,52,Female,29.6,143.0,219.0,High,No,Negative
50,68,Male,25.5,124.0,199.0,Normal,Yes,Positive

In [120]:
df.isna().sum()

Age              0
Sex              0
BMI              1
BloodPressure    1
Cholesterol      1
BloodSugar       1
FamilyHistory    0
CancerStatus     0
dtype: int64

In [121]:
df = df.dropna()

In [122]:
df

,Age,Sex,BMI,BloodPressure,Cholesterol,BloodSugar,FamilyHistory,CancerStatus
PatientID,,,,,,,,
1,45,Male,25.6,120.0,190.0,Normal,Yes,Positive
2,55,Female,29.8,140.0,220.0,High,No,Negative
3,60,Male,27.3,130.0,210.0,Normal,Yes,Positive
4,35,Female,22.5,110.0,180.0,Normal,No,Negative
5,50,Male,31.1,150.0,240.0,High,Yes,Positive
6,65,Male,26.5,125.0,200.0,High,Yes,Positive
7,40,Female,24.9,115.0,170.0,Normal,No,Negative
8,70,Male,27.9,135.0,230.0,High,Yes,Positive
13,47,Male,25.1,122.0,195.0,Normal,Yes,Positive
14,57,Female,27.4,138.0,215.0,Normal,No,Negative
15,64,Male,28.6,132.0,225.0,High,Yes,Positive
16,38,Female,23.8,114.0,175.0,Normal,No,Negative
17,48,Male,30.2,148.0,230.0,High,Yes,Positive
18,69,Male,26.2,128.0,205.0,Normal,Yes,Positive
19,42,Female,29.7,142.0,218.0,High,No,Negative
20,56,Male,24.5,123.0,198.0,Normal,Yes,Positive
21,61,Female,27.9,136.0,227.0,Normal,No,Negative
22,36,Male,25.9,126.0,202.0,High,Yes,Positive
23,52,Male,22.3,108.0,178.0,Normal,No,Negative
24,63,Female,30.4,144.0,235.0,High,Yes,Positive
25,41,Male,27.1,134.0,215.0,Normal,Yes,Positive
26,59,Female,26.6,130.0,212.0,Normal,No,Negative
27,68,Male,28.9,139.0,222.0,High,Yes,Positive
28,37,Male,24.2,120.0,192.0,Normal,Yes,Positive
29,49,Female,29.5,141.0,217.0,High,No,Negative
30,54,Male,25.8,124.0,200.0,Normal,Yes,Positive
31,66,Female,28.2,137.0,224.0,Normal,No,Negative
32,39,Male,27.6,133.0,210.0,High,Yes,Positive
33,51,Male,23.7,109.0,180.0,Normal,No,Negative
34,70,Female,30.1,147.0,231.0,High,Yes,Positive
35,43,Male,26.4,129.0,208.0,Normal,Yes,Positive
36,58,Female,29.3,140.0,216.0,High,No,Negative
37,67,Male,26.7,131.0,214.0,Normal,Yes,Positive
38,44,Male,25.7,121.0,196.0,Normal,Yes,Positive
39,60,Female,28.7,135.0,226.0,Normal,No,Negative
40,50,Male,24.4,125.0,198.0,High,Yes,Positive
41,65,Female,27.8,138.0,220.0,High,No,Negative
42,35,Male,26.1,127.0,204.0,Normal,Yes,Positive
43,55,Male,22.8,111.0,182.0,Normal,No,Negative
44,63,Female,30.6,146.0,236.0,High,Yes,Positive
45,40,Male,27.4,132.0,216.0,Normal,Yes,Positive
46,57,Female,26.9,131.0,213.0,Normal,No,Negative
47,66,Male,28.1,136.0,223.0,High,Yes,Positive
48,38,Male,24.3,119.0,194.0,Normal,Yes,Positive
49,52,Female,29.6,143.0,219.0,High,No,Negative
50,68,Male,25.5,124.0,199.0,Normal,Yes,Positive

In [123]:
df.to_csv('Patients.csv')

In [124]:
cursor.close()
connection.close()

#Question 2

In [125]:
import requests
import re

In [126]:
url  = 'http://universities.hipolabs.com/search?country=India'

In [127]:
response = requests.get(url)

In [128]:
if response.status_code == 200:
  json_data = response.json()
  json_data
  names= [item['name'] for item in json_data]
  provinces= [item['state-province'] for item in json_data]

In [129]:
df2 = pd.DataFrame({'Name':names, 'State-Province':provinces})

In [130]:
df2 = df2.dropna()

In [131]:
df2.to_csv('Universities and Their Provinces.csv')

#Question 3

In [132]:
from bs4 import BeautifulSoup
url2 = 'https://books.toscrape.com/catalogue/category/books/mystery_3/page-1.html'
url3 = 'https://books.toscrape.com/catalogue/category/books/mystery_3/page-2.html'
response2 = requests.get(url2)
response3 = requests.get(url3)
soup = BeautifulSoup(response2.text, 'html.parser')
soup2 = BeautifulSoup(response3.text, 'html.parser')

In [133]:
books = soup.find_all('article')
books2 = soup2.find_all('article')

In [134]:
ratings= []
titles= [a.find('h3').find('a').string for a in books]
    #title of the book, the price and the review score


prices = [a.find('p', attrs={'class': 'price_color'}).string[1:] for a in books]
all_classes = soup.find_all(class_=True)
class_names = [i['class'] for i in all_classes]
for a in class_names:
  if a[0] == 'star-rating':
    ratings.append(a[1])

for b in books2:
  titles.append(b.find('h3').find('a').string)
  prices.append(b.find('p', attrs={'class': 'price_color'}).string[1:])

all_classes2 = soup2.find_all(class_=True)
class_names2 = [i['class'] for i in all_classes2]
for b in class_names2:
  if b[0] == 'star-rating':
    ratings.append(b[1])

In [135]:
df3 = pd.DataFrame({'Title':titles, 'Price':prices, 'Rating': ratings})

In [136]:
df3

                                   Title   Price Rating
0                          Sharp Objects  £47.82   Four
1                    In a Dark, Dark ...  £19.63    One
2                    The Past Never Ends  £56.50   Four
3                       A Murder in Time  £16.64    One
4                The Murder of Roger ...  £44.10   Four
5                The Last Mile (Amos ...  £54.21    Two
6        That Darkness (Gardiner and ...  £13.92    One
7               Tastes Like Fear (DI ...  £10.69    One
8                  A Time of Torment ...  £48.35   Five
9                 A Study in Scarlet ...  £16.73    Two
10      Poisonous (Max Revere Novels ...  £26.80  Three
11                Murder at the 42nd ...  £54.36   Four
12                           Most Wanted  £35.28  Three
13             Hide Away (Eve Duncan ...  £11.84    One
14          Boar Island (Anna Pigeon ...  £59.48  Three
15                             The Widow  £27.26    Two
16                     Playing with Fire  £13.71  Three
17            What Happened on Beale ...  £25.37   Five
18         The Bachelor Girl's Guide ...  £52.30   Five
19      Delivering the Truth (Quaker ...  £20.89   Four
20          The Mysterious Affair at ...  £24.80   Four
21              In the Woods (Dublin ...  £38.38    Two
22     The Silkworm (Cormoran Strike ...  £23.05   Five
23                            The Exiled  £43.45  Three
24    The Cuckoo's Calling (Cormoran ...  £19.21    One
25     Extreme Prey (Lucas Davenport ...  £25.40  Three
26          Career of Evil (Cormoran ...  £24.72    Two
27                 The No. 1 Ladies' ...  £57.70   Four
28                     The Girl You Lost  £12.29   Five
29                   The Girl In The ...  £15.85  Three
30  Blood Defense (Samantha Brinkman ...  £20.30  Three
31               1st to Die (Women's ...  £53.98    One

In [138]:
df3.to_csv('Mystery Books.csv')